In [1]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 2.2.3
NumPy: 2.4.6

In [2]:
df = pd.read_csv("raw/upi_transactions_2024.csv")

print("Dataset Shape:", df.shape)

Dataset Shape: (250000, 17)

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("raw/upi_transactions_2024.csv")

print("Dataset Shape:", df.shape)

Dataset Shape: (250000, 17)

In [4]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

In [5]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction id      250000 non-null  object
 1   timestamp           250000 non-null  object
 2   transaction type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount (INR)        250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
 10  receiver_bank       250000 non-null  object
 11  device_type         250000 non-null  object
 12  network_type        250000 non-null  object
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  object
 16  is_weekend          250000 non-null  int64
dtypes: int64(4), object(13)
memory usage: 32.4+ MB

In [8]:
missing = df.isnull().sum()

print(missing)

transaction id        0
timestamp             0
transaction type      0
merchant_category     0
amount (INR)          0
transaction_status    0
sender_age_group      0
receiver_age_group    0
sender_state          0
sender_bank           0
receiver_bank         0
device_type           0
network_type          0
fraud_flag            0
hour_of_day           0
day_of_week           0
is_weekend            0
dtype: int64

In [9]:
missing_percent = (df.isnull().sum() / len(df)) * 100

print(missing_percent)

transaction id        0.0
timestamp             0.0
transaction type      0.0
merchant_category     0.0
amount (INR)          0.0
transaction_status    0.0
sender_age_group      0.0
receiver_age_group    0.0
sender_state          0.0
sender_bank           0.0
receiver_bank         0.0
device_type           0.0
network_type          0.0
fraud_flag            0.0
hour_of_day           0.0
day_of_week           0.0
is_weekend            0.0
dtype: float64

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [16]:
print(
    "Duplicate transaction IDs:",
    df["transaction id"].duplicated().sum()
)

Duplicate transaction IDs: 0

In [12]:
print(df["fraud_flag"].value_counts())

fraud_flag
0    249520
1       480
Name: count, dtype: int64

In [13]:
print(
    df["fraud_flag"].value_counts(normalize=True) * 100
)

fraud_flag
0    99.808
1     0.192
Name: proportion, dtype: float64

In [17]:
categorical_columns = [
    "transaction type",
    "merchant_category",
    "transaction_status",
    "sender_age_group",
    "receiver_age_group",
    "sender_state",
    "sender_bank",
    "receiver_bank",
    "device_type",
    "network_type"
]

for col in categorical_columns:
    print("\n", col)
    print(df[col].value_counts())

 transaction type
transaction type
P2P             112445
P2M              87660
Bill Payment     37368
Recharge         12527
Name: count, dtype: int64

 merchant_category
merchant_category
Grocery          49966
Food             37464
Shopping         29872
Fuel             25063
Other            24828
Utilities        22338
Transport        20105
Entertainment    20103
Healthcare       12663
Education         7598
Name: count, dtype: int64

 transaction_status
transaction_status
SUCCESS    237624
FAILED      12376
Name: count, dtype: int64

 sender_age_group
sender_age_group
26-35    87432
36-45    62873
18-25    62345
46-55    24841
56+      12509
Name: count, dtype: int64

 receiver_age_group
receiver_age_group
26-35    87864
18-25    62611
36-45    62151
46-55    24823
56+      12551
Name: count, dtype: int64

 sender_state
sender_state
Maharashtra       37427
Uttar Pradesh     30125
Karnataka         29756
Tamil Nadu        25367
Delhi             24870
Telangana         22435
Gujarat           20061
Andhra Pradesh    20006
Rajasthan         19981
West Bengal       19972
Name: count, dtype: int64

 sender_bank
sender_bank
SBI         62693
HDFC        37485
ICICI       29769
IndusInd    25173
Axis        25042
PNB         24946
Yes Bank    24860
Kotak       20032
Name: count, dtype: int64

 receiver_bank
receiver_bank
SBI         62378
HDFC        37651
ICICI       29944
IndusInd    25086
Yes Bank    25009
Axis        24992
PNB         24802
Kotak       20138
Name: count, dtype: int64

 device_type
device_type
Android    187777
iOS         49613
Web         12610
Name: count, dtype: int64

 network_type
network_type
4G      149813
5G       62582
WiFi     25134
3G       12471
Name: count, dtype: int64

In [18]:
print(df["timestamp"].head())
print(df["timestamp"].dtype)

0    2024-10-08 15:17:28
1    2024-04-11 06:56:00
2    2024-04-02 13:27:18
3    2024-01-07 10:09:17
4    2024-01-23 19:04:23
Name: timestamp, dtype: object
object

In [19]:
df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    errors="coerce"
)

In [20]:
print(df["timestamp"].dtype)

datetime64[ns]

In [15]:
print(df.columns.tolist())

['transaction id', 'timestamp', 'transaction type', 'merchant_category', 'amount (INR)', 'transaction_status', 'sender_age_group', 'receiver_age_group', 'sender_state', 'sender_bank', 'receiver_bank', 'device_type', 'network_type', 'fraud_flag', 'hour_of_day', 'day_of_week', 'is_weekend']

In [21]:
print(
    "Invalid timestamps:",
    df["timestamp"].isna().sum()
)

Invalid timestamps: 0

In [22]:
df["calculated_hour"] = df["timestamp"].dt.hour

df["calculated_day"] = df["timestamp"].dt.day_name()

df["calculated_weekend"] = (
    df["timestamp"].dt.dayofweek >= 5
).astype(int)

In [23]:
print(
    "Hour mismatches:",
    (df["hour_of_day"] != df["calculated_hour"]).sum()
)

print(
    "Day mismatches:",
    (df["day_of_week"] != df["calculated_day"]).sum()
)

print(
    "Weekend mismatches:",
    (df["is_weekend"] != df["calculated_weekend"]).sum()
)

Hour mismatches: 0
Day mismatches: 0
Weekend mismatches: 0

In [24]:
print(
    "Zero/negative amounts:",
    (df["amount (INR)"] <= 0).sum()
)

Zero/negative amounts: 0

In [25]:
df.groupby("fraud_flag")["amount (INR)"].describe()

,count,mean,std,min,25%,50%,75%,max
fraud_flag,,,,,,,,
0,249520.0,1311.395391,1847.210565,10.0,288.0,629.0,1596.0,42099.0
1,480.0,1499.231250,2240.707939,28.0,260.0,618.5,1673.5,17718.0

In [26]:
pd.crosstab(
    df["merchant_category"],
    df["fraud_flag"],
    normalize="index"
) * 100

fraud_flag                 0         1
merchant_category
Education          99.789418  0.210582
Entertainment      99.801025  0.198975
Food               99.805146  0.194854
Fuel               99.808483  0.191517
Grocery            99.811872  0.188128
Healthcare         99.834163  0.165837
Other              99.798614  0.201386
Shopping           99.792448  0.207552
Transport          99.786123  0.213877
Utilities          99.852270  0.147730

In [27]:
pd.crosstab(
    df["device_type"],
    df["fraud_flag"],
    normalize="index"
) * 100

fraud_flag           0         1
device_type
Android      99.806153  0.193847
Web          99.793814  0.206186
iOS          99.818596  0.181404

In [28]:
pd.crosstab(
    df["hour_of_day"],
    df["fraud_flag"],
    normalize="index"
) * 100

fraud_flag           0         1
hour_of_day
0            99.763872  0.236128
1            99.732620  0.267380
2            99.821958  0.178042
3            99.695586  0.304414
4            99.919808  0.080192
5            99.942595  0.057405
6            99.857184  0.142816
7            99.769094  0.230906
8            99.784405  0.215595
9            99.808612  0.191388
10           99.856157  0.143843
11           99.834640  0.165360
12           99.828728  0.171272
13           99.833754  0.166246
14           99.816946  0.183054
15           99.746515  0.253485
16           99.778445  0.221555
17           99.798255  0.201745
18           99.845494  0.154506
19           99.797476  0.202524
20           99.800065  0.199935
21           99.784655  0.215345
22           99.754378  0.245622
23           99.845281  0.154719

In [30]:
    print(df.columns.tolist())

['transaction id', 'timestamp', 'transaction type', 'merchant_category', 'amount (INR)', 'transaction_status', 'sender_age_group', 'receiver_age_group', 'sender_state', 'sender_bank', 'receiver_bank', 'device_type', 'network_type', 'fraud_flag', 'hour_of_day', 'day_of_week', 'is_weekend', 'calculated_hour', 'calculated_day', 'calculated_weekend']

In [31]:
df.drop(
    columns=[
        "calculated_hour",
        "calculated_day",
        "calculated_weekend"
    ],
    inplace=True
)

In [32]:
df["is_night_transaction"] = (
    (df["hour_of_day"] < 6) |
    (df["hour_of_day"] >= 23)
).astype(int)

In [33]:
high_amount_threshold = df["amount (INR)"].quantile(0.95)

df["is_high_amount"] = (
    df["amount (INR)"] > high_amount_threshold
).astype(int)

print("High amount threshold:", high_amount_threshold)

High amount threshold: 4687.049999999988

In [34]:
print("Final rows:", len(df))
print("Final columns:", len(df.columns))

df.head()

Final rows: 250000
Final columns: 19

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend,is_night_transaction,is_high_amount
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0,0,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0,0,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0,0,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1,0,0
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0,0,0

In [35]:
missing = df.isnull().sum()

print(missing[missing > 0])

Series([], dtype: int64)

In [36]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [37]:
print("Duplicate Transaction IDs:", df["transaction id"].duplicated().sum())

Duplicate Transaction IDs: 0

In [38]:
categorical_cols = [
    "transaction type",
    "merchant_category",
    "transaction_status",
    "sender_age_group",
    "receiver_age_group",
    "sender_state",
    "sender_bank",
    "receiver_bank",
    "device_type",
    "network_type",
    "day_of_week"
]

df_encoded = pd.get_dummies(
    df,
    columns=categorical_cols,
    drop_first=True
)

print(df_encoded.shape)

(250000, 63)

In [39]:
categorical_cols = [
    "transaction type",
    "merchant_category",
    "transaction_status",
    "sender_age_group",
    "receiver_age_group",
    "sender_state",
    "sender_bank",
    "receiver_bank",
    "device_type",
    "network_type",
    "day_of_week"
]

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Convert True/False to 0/1
df = df.astype({col: int for col in df.select_dtypes("bool").columns})

# Remove transaction ID
df.drop(columns=["transaction id"], inplace=True)

# Save
df.to_csv("processed/upi_transactions_processed.csv", index=False)

print("Done!")
print(df.shape)

Done!
(250000, 62)

In [40]:
print(df.columns.tolist())

['timestamp', 'amount (INR)', 'fraud_flag', 'hour_of_day', 'is_weekend', 'is_night_transaction', 'is_high_amount', 'transaction type_P2M', 'transaction type_P2P', 'transaction type_Recharge', 'merchant_category_Entertainment', 'merchant_category_Food', 'merchant_category_Fuel', 'merchant_category_Grocery', 'merchant_category_Healthcare', 'merchant_category_Other', 'merchant_category_Shopping', 'merchant_category_Transport', 'merchant_category_Utilities', 'transaction_status_SUCCESS', 'sender_age_group_26-35', 'sender_age_group_36-45', 'sender_age_group_46-55', 'sender_age_group_56+', 'receiver_age_group_26-35', 'receiver_age_group_36-45', 'receiver_age_group_46-55', 'receiver_age_group_56+', 'sender_state_Delhi', 'sender_state_Gujarat', 'sender_state_Karnataka', 'sender_state_Maharashtra', 'sender_state_Rajasthan', 'sender_state_Tamil Nadu', 'sender_state_Telangana', 'sender_state_Uttar Pradesh', 'sender_state_West Bengal', 'sender_bank_HDFC', 'sender_bank_ICICI', 'sender_bank_IndusInd', 'sender_bank_Kotak', 'sender_bank_PNB', 'sender_bank_SBI', 'sender_bank_Yes Bank', 'receiver_bank_HDFC', 'receiver_bank_ICICI', 'receiver_bank_IndusInd', 'receiver_bank_Kotak', 'receiver_bank_PNB', 'receiver_bank_SBI', 'receiver_bank_Yes Bank', 'device_type_Web', 'device_type_iOS', 'network_type_4G', 'network_type_5G', 'network_type_WiFi', 'day_of_week_Monday', 'day_of_week_Saturday', 'day_of_week_Sunday', 'day_of_week_Thursday', 'day_of_week_Tuesday', 'day_of_week_Wednesday']

In [41]:
df.to_csv("processed/upi_transactions_ml_ready.csv", index=False)

In [1]:
df19 = pd.read_csv("raw/upi_transactions_2024.csv")

NameError: name 'pd' is not defined

In [2]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)

Pandas: 2.2.3

In [3]:
import pandas as pd
import os

input_file = "raw/upi_transactions_2024.csv"
output_file = "processed/upi_transactions_processed.csv"

os.makedirs("processed", exist_ok=True)

first_chunk = True

for chunk in pd.read_csv(input_file, chunksize=50000):

    # Timestamp cleaning
    chunk["timestamp"] = pd.to_datetime(
        chunk["timestamp"],
        errors="coerce"
    )

    # Night transaction
    chunk["is_night_transaction"] = (
        (chunk["hour_of_day"] < 6) |
        (chunk["hour_of_day"] >= 23)
    ).astype(int)

    # High amount transaction
    threshold = chunk["amount (INR)"].quantile(0.95)

    chunk["is_high_amount"] = (
        chunk["amount (INR)"] > threshold
    ).astype(int)

    # Save
    chunk.to_csv(
        output_file,
        mode="w" if first_chunk else "a",
        header=first_chunk,
        index=False
    )

    first_chunk = False

print("DONE!")

DONE!

In [4]:
df_check = pd.read_csv("processed/upi_transactions_processed.csv")

print("Rows:", len(df_check))
print("Columns:", len(df_check.columns))
print(df_check.columns.tolist())

Rows: 250000
Columns: 19
['transaction id', 'timestamp', 'transaction type', 'merchant_category', 'amount (INR)', 'transaction_status', 'sender_age_group', 'receiver_age_group', 'sender_state', 'sender_bank', 'receiver_bank', 'device_type', 'network_type', 'fraud_flag', 'hour_of_day', 'day_of_week', 'is_weekend', 'is_night_transaction', 'is_high_amount']

In [5]:
df_check.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend,is_night_transaction,is_high_amount
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0,0,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0,0,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0,0,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1,0,0
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0,0,0

In [6]:
print(df_check["fraud_flag"].value_counts())

fraud_flag
0    249520
1       480
Name: count, dtype: int64